# Generated by Django 2.2 on 2020-01-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='is_returned',
            field=models.CharField(default='', max_length=200),
        ),
    ]
