# Generated by Django 2.2 on 2020-02-09 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(height_field=500, upload_to='pictures/%Y/%m/%d', width_field=500)),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('CM', 'Comedy'), ('CR', 'Crime'), ('DR', 'Drama'), ('HS', 'Historical'), ('HR', 'Horror'), ('MC', 'Musicals'), ('SC', 'Science'), ('WR', 'War'), ('WN', 'Westerns')], max_length=2)),
                ('description', models.TextField()),
                ('release_year', models.DateField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('available_seats', models.PositiveIntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='filmsessions.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='filmsessions.FilmSession')),
            ],
        ),
        migrations.AddField(
            model_name='filmsession',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='filmsessions.Hall'),
        ),
    ]
