# Generated by Django 2.2 on 2020-02-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='picture',
            field=models.ImageField(default='default.png', height_field=500, upload_to='pictures/%Y/%m/%d', width_field=500),
        ),
    ]
