# Generated by Django 2.2 on 2020-02-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsessions', '0005_auto_20200209_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsession',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
