# Generated by Django 2.2 on 2020-02-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsessions', '0007_auto_20200209_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsession',
            name='available_seats',
            field=models.IntegerField(blank=True),
        ),
    ]
