# Generated by Django 2.2 on 2020-02-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsessions', '0008_auto_20200211_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsession',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
