# Generated by Django 3.0.2 on 2020-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='token',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
