# Generated by Django 2.2 on 2020-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
