# Generated by Django 3.0.2 on 2020-01-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'visitor'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='age_limit',
            field=models.IntegerField(default=8),
        ),
    ]
