# Generated by Django 3.0.2 on 2020-01-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200109_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='animal',
            new_name='animals',
        ),
    ]
