# Generated by Django 3.0.2 on 2020-01-09 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200109_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-arrived_at']},
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
